quarkus.application.name=quarkus-coding-harness-template

quarkus.log.console.json.enabled=true
quarkus.log.console.json.pretty-print=false

quarkus.otel.traces.exporter=none
quarkus.otel.logs.enabled=false
quarkus.otel.logs.handler.enabled=false
quarkus.otel.logs.exporter=none
%test.quarkus.otel.traces.exporter=cdi
%test.quarkus.otel.simple=true
